MicroServiceProject/Source/UserInterface/MP.UserInterface.CoreUI/Models/GatewayClientHelper.cs
using Microsoft.Extensions.Configuration;

namespace MP.UserInterface.CoreUI.Models
{
    public class GatewayClientHelper
    {
        private readonly IConfiguration _configuration;

        public GatewayClientHelper(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public enum Actions
        {
            CreditCardInsert,
            CreditCardUpdate,
            CreditCardRemove,
            CreditCardList,
            CreditCardListByFinancialScore,
            CreditCardListByType,
            CreditCardListByBank,
            CustomerInsert,
            CustomerUpdate,
            CustomerRemove,
            CustomerList,
            CustomerLogin,
            CustomerByToken,
            CustomerByIdentity,
            FinancialRatingCalculate,
            AuthLogin,
            AuthCheck,
            AuthRefresh,
            AuthTestUser
        }

        public string SetUrl(Actions action)
        {
            string environment = _configuration.GetSection("Environment").Value;
            string baseUrl = string.Empty;
            switch (environment)
            {
                case "Dev":
                    baseUrl = "http://localhost:51214";
                    break;

                case "Test":
                    baseUrl = "https://test.microservisproject.com";
                    break;

                case "PreProd":
                    baseUrl = "https://preprod.microservisproject.com";
                    break;

                case "Prod":
                    baseUrl = "https://microservisproject.com";
                    break;

                default:
                    break;
            }

            string afterUrl = string.Empty;
            switch (action)
            {
                case Actions.CreditCardInsert:
                    afterUrl = "/creditcard/insert";
                    break;

                case Actions.CreditCardUpdate:
                    afterUrl = "/creditcard/update";
                    break;

                case Actions.CreditCardRemove:
                    afterUrl = "/creditcard/remove";
                    break;

                case Actions.CreditCardList:
                    afterUrl = "/creditcard/list";
                    break;

                case Actions.CreditCardListByFinancialScore:
                    afterUrl = "/creditcard/by-financial-score";
                    break;

                case Actions.CreditCardListByType:
                    afterUrl = "/creditcard/by-type";
                    break;

                case Actions.CreditCardListByBank:
                    afterUrl = "/creditcard/by-bank";
                    break;

                case Actions.CustomerInsert:
                    afterUrl = "/customer/insert";
                    break;

                case Actions.CustomerUpdate:
                    afterUrl = "/customer/update";
                    break;

                case Actions.CustomerRemove:
                    afterUrl = "/customer/remove";
                    break;

                case Actions.CustomerList:
                    afterUrl = "/customer/list";
                    break;

                case Actions.CustomerLogin:
                    afterUrl = "/customer/login";
                    break;

                case Actions.CustomerByToken:
                    afterUrl = "/customer/by-token";
                    break;

                case Actions.CustomerByIdentity:
                    afterUrl = "/customer/by-identity";
                    break;

                case Actions.FinancialRatingCalculate:
                    afterUrl = "/financialrating/calculate";
                    break;

                case Actions.AuthLogin:
                    afterUrl = "/auth/login";
                    break;

                case Actions.AuthCheck:
                    afterUrl = "/auth/check";
                    break;

                case Actions.AuthRefresh:
                    afterUrl = "/auth/refresh";
                    break;

                case Actions.AuthTestUser:
                    afterUrl = "/auth/test-user";
                    break;

                default:
                    break;
            }

            return baseUrl + afterUrl;
        }
    }
}

MicroServiceProject/Source/UserInterface/MP.UserInterface.CoreUI/Components/LoginViewComponent/LoginViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MP.UserInterface.CoreUI.Components.LoginViewComponent
{
    [ViewComponent(Name = "LoginViewComponent")]
    public class LoginViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("LoginViewComponent");
        }
    }
}

MicroServiceProject/Source/UserInterface/MP.UserInterface.CoreUI/Controllers/ApplyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MP.UserInterface.CoreUI.Controllers
{
    [Authorize]
    public class ApplyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Calculate()
        {
            return View();
        }
    }
}

MicroServiceProject/Source/UserInterface/MP.UserInterface.CoreUI/Controllers/CreditCardController.cs
using Microsoft.AspNetCore.Mvc;

namespace MP.UserInterface.CoreUI.Controllers
{
    [Route("Home")]
    public class CreditCardController : Controller
    {
        [Route("/")]
        public IActionResult List()
        {
            return View();
        }

        [Route("~/CreditCard/{cardName}")]
        public IActionResult Detail(string cardName)
        {
            return View();
        }
    }
}

MicroServiceProject/Source/UserInterface/MP.UserInterface.CoreUI/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MP.Core.Application.ViewModels;
using MP.Core.Domain.Entities;
using MP.UserInterface.CoreUI.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Threading.Tasks;

namespace MP.UserInterface.CoreUI.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IConfiguration _configuration;

        public CustomerController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            string response = string.Empty;
            string url = new GatewayClientHelper(_configuration).SetUrl(GatewayClientHelper.Actions.AuthLogin);
            using (HttpClient httpClient = new HttpClient())
            {
                Dictionary<string, string> loginValues = new Dictionary<string, string>
                {
                   { "Email", model.Email },
                   { "Password", model.Password }
                };
                FormUrlEncodedContent formUrlEncodedContent = new FormUrlEncodedContent(loginValues);
                HttpResponseMessage httpResponseMessage = await httpClient.PostAsync(url, formUrlEncodedContent);
                response = await httpResponseMessage.Content.ReadAsStringAsync();
            }

            if (!string.IsNullOrEmpty(response))
            {
                Customer customer = JsonConvert.DeserializeObject<Customer>(response);
                CookieOptions option = new CookieOptions
                {
                    HttpOnly = true,
                    Secure = true,
                    Expires = DateTime.Now.AddHours(4)
                };
                Response.Cookies.Append("token", customer.Token, option);
                return Ok();
            }

            return BadRequest();
        }

        [Authorize]
        public IActionResult Logout()
        {
            Response.Cookies.Delete("token");
            return RedirectToAction("List", "CreditCard");
        }

        [Authorize]
        public IActionResult Applications()
        {
            return View();
        }
    }
}

MicroServiceProject/Source/UserInterface/MP.UserInterface.CoreUI/ViewComponents/LoginViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MP.UserInterface.CoreUI.ViewComponents
{
    public class LoginViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("LoginViewComponent");
        }
    }
}

MicroServiceProject/Source/UserInterface/MP.UserInterface.CoreUI/Views/Apply/Index.cshtml
@section HeadTags{

}

@section BodyExtra{

}

@section Styles{

}

@section Scripts{

}

MicroServiceProject/Source/UserInterface/MP.UserInterface.CoreUI/Views/CreditCard/Detail.cshtml
@section HeadTags{

}

@section BodyExtra{

}

@section Styles{

}

@section Scripts{

}

MicroServiceProject/Source/UserInterface/MP.UserInterface.CoreUI/Views/CreditCard/List.cshtml
@section HeadTags{

}

@section BodyExtra{

}

@section Styles{

}

@section Scripts{

}

MicroServiceProject/Source/UserInterface/MP.UserInterface.CoreUI/Views/Customer/Applications.cshtml
@section HeadTags{

}

@section BodyExtra{

}

@section Styles{

}

@section Scripts{

}

MicroServiceProject/Source/UserInterface/MP.UserInterface.CoreUI/Views/Shared/Components/LoginViewComponent/LoginViewComponent.cshtml
<form asp-controller="Customer" asp-action="Login" method="post" class="d-flex">
    <input class="form-control me-2" id="LoginEmail" placeholder="Email Address" type="email" required />
    <input class="form-control me-2" id="LoginPassword" placeholder="Password" type="password" required />
	<button type="submit" class="btn btn-outline-success">Login</button>
</form>

MicroServiceProject/Source/UserInterface/MP.UserInterface.CoreUI/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	@RenderSection("HeadTags", required: true)
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	@RenderSection("Styles", required: false)
</head>
<body>
	<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
		<div class="container">
			<a class="navbar-brand" href="#">MicroService Demo Project</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarCollapse">
				<ul class="navbar-nav me-auto mb-2 mb-md-0">
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="#">Credit Cards</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Applications</a>
					</li>
				</ul>
				@await Component.InvokeAsync("LoginViewComponent")
			</div>
		</div>
	</nav>
	<main class="container">
		@RenderBody()
		@RenderSection("BodyExtra", required: false)
	</main>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>